/*
 * File Context:
 * Purpose: Defines shared configuration for Product Field.Config.
 * Primary Functionality: Exports static configuration values that other modules consume directly.
 * Interlinked With: src/shared/types/index.ts
 * Role: shared configuration.
 */
import type { ProductFieldConfig, ProductStockDisplaySettings } from '../types';

export const defaultProductFieldConfig: ProductFieldConfig[] = [
  {
    fieldKey: 'name',
    label: 'Product Name',
    description: 'Primary product title shown in the product card.',
    isVisible: true,
    sortOrder: 1,
  },
  {
    fieldKey: 'productId',
    label: 'Product ID',
    description: 'Internal ERP product identifier shown below the title.',
    isVisible: true,
    sortOrder: 2,
  },
  {
    fieldKey: 'productAlias',
    label: 'Product Alias',
    description: 'Alternate product alias returned by ERP.',
    isVisible: false,
    sortOrder: 3,
  },
  {
    fieldKey: 'printName',
    label: 'Print Name',
    description: 'Print-friendly product name from ERP.',
    isVisible: false,
    sortOrder: 4,
  },
  {
    fieldKey: 'unit',
    label: 'Unit',
    description: 'Selling unit such as Pcs., Kg, or Box.',
    isVisible: true,
    sortOrder: 5,
  },
  {
    fieldKey: 'unitCode',
    label: 'Unit Code',
    description: 'ERP unit code used for unit identification.',
    isVisible: false,
    sortOrder: 31,
  },
  {
    fieldKey: 'price',
    label: 'Display Price',
    description: 'Resolved selling price used for the primary price display.',
    isVisible: true,
    sortOrder: 6,
  },
  {
    fieldKey: 'salesPrice',
    label: 'Sales Price',
    description: 'Raw sales price returned by ERP.',
    isVisible: false,
    sortOrder: 7,
  },
  {
    fieldKey: 'purchasePrice',
    label: 'Purchase Price',
    description: 'Purchase price returned by ERP.',
    isVisible: false,
    sortOrder: 8,
  },
  {
    fieldKey: 'mrp',
    label: 'MRP',
    description: 'Secondary MRP line shown when it is different from the selling price.',
    isVisible: true,
    sortOrder: 9,
  },
  {
    fieldKey: 'stock',
    label: 'Stock',
    description: 'Available stock badge shown on the product card.',
    isVisible: true,
    sortOrder: 10,
  },
  {
    fieldKey: 'groupName',
    label: 'Group Name',
    description: 'Product group or category label shown in the meta line.',
    isVisible: true,
    sortOrder: 11,
  },
  {
    fieldKey: 'groupId',
    label: 'Group ID',
    description: 'ERP product group identifier.',
    isVisible: false,
    sortOrder: 12,
  },
  {
    fieldKey: 'mcName',
    label: 'MC Name',
    description: 'Multi-company or related ERP name when available.',
    isVisible: false,
    sortOrder: 13,
  },
  {
    fieldKey: 'mcCode',
    label: 'MC Code',
    description: 'Multi-company or related ERP code.',
    isVisible: false,
    sortOrder: 14,
  },
  {
    fieldKey: 'taxName',
    label: 'Tax Name',
    description: 'Tax label such as GST 12%.',
    isVisible: false,
    sortOrder: 15,
  },
  {
    fieldKey: 'taxId',
    label: 'Tax ID',
    description: 'ERP tax identifier.',
    isVisible: false,
    sortOrder: 16,
  },
  {
    fieldKey: 'hsnCode',
    label: 'HSN Code',
    description: 'HSN/SAC code returned by ERP.',
    isVisible: false,
    sortOrder: 17,
  },
  {
    fieldKey: 'taxRate',
    label: 'Tax Rate',
    description: 'GST or tax percentage shown in the meta line.',
    isVisible: true,
    sortOrder: 18,
  },
  {
    fieldKey: 'apiPrice',
    label: 'ERP Price',
    description: 'Raw product_price value from ERP.',
    isVisible: false,
    sortOrder: 19,
  },
  {
    fieldKey: 'salesDiscount',
    label: 'Sales Discount',
    description: 'Sales discount value from ERP.',
    isVisible: false,
    sortOrder: 20,
  },
  {
    fieldKey: 'salesMarkup',
    label: 'Sales Markup',
    description: 'Sales markup value from ERP.',
    isVisible: false,
    sortOrder: 21,
  },
  {
    fieldKey: 'purchaseDiscount',
    label: 'Purchase Discount',
    description: 'Purchase discount value from ERP.',
    isVisible: false,
    sortOrder: 22,
  },
  {
    fieldKey: 'descriptionLine1',
    label: 'Description Line 1',
    description: 'First extra description line from ERP.',
    isVisible: false,
    sortOrder: 23,
  },
  {
    fieldKey: 'descriptionLine2',
    label: 'Description Line 2',
    description: 'Second extra description line from ERP.',
    isVisible: false,
    sortOrder: 24,
  },
  {
    fieldKey: 'descriptionLine3',
    label: 'Description Line 3',
    description: 'Third extra description line from ERP.',
    isVisible: false,
    sortOrder: 25,
  },
  {
    fieldKey: 'descriptionLine4',
    label: 'Description Line 4',
    description: 'Fourth extra description line from ERP.',
    isVisible: false,
    sortOrder: 26,
  },
  {
    fieldKey: 'createdBy',
    label: 'Created By',
    description: 'ERP creator user name.',
    isVisible: false,
    sortOrder: 27,
  },
  {
    fieldKey: 'creationTime',
    label: 'Creation Time',
    description: 'ERP creation timestamp.',
    isVisible: false,
    sortOrder: 28,
  },
  {
    fieldKey: 'modifiedBy',
    label: 'Modified By',
    description: 'ERP modifier user name.',
    isVisible: false,
    sortOrder: 29,
  },
  {
    fieldKey: 'modificationTime',
    label: 'Modification Time',
    description: 'ERP modification timestamp.',
    isVisible: false,
    sortOrder: 30,
  },
];

export const defaultProductStockDisplaySettings: ProductStockDisplaySettings = {
  showExactStockQuantity: true,
  showOutOfStockProducts: true,
};
